apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    rollingUpdate:
      # Reverse Rolling Update
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: ujhgj/hipster-paymentservice:v0.0.2
          env:
            - name: PORT
              value: "50051"