apiVersion: v1
kind: Pod
metadata:
  name: pod-test-app
  labels: {}
spec:
  initContainers:
  - name: init
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  containers:
  - name: test-app
    image: mezorg/test_app_1_otus:v2-release
    volumeMounts:
    - name: app
      mountPath: /app
    ports:
      - name: http
        containerPort: 8000
        protocol: TCP
      #- name: https
      #  containerPort: 443
      #  protocol: TCP
  volumes:
  - name: app
    emptyDir: {}
